name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: your-app-name  # Replace with your Heroku app name
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku login -i
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
